- name: Configure YUM repos
 ansible.builtin.shell: curl -fssL https://rpm.nodesource.com/setup.lts.x | bash -

- name: Install NodeJS
 ansible.builtin.yum:
  name:
   - nodejs
   - gcc-c++
  state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project Application User