- name: Configure YUM repos.
  ansible.builtin.shell: curl -fssL https://rpm.nodesource.com/setup.lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
    name:
    - nodejs
    - gcc-c++
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project Application Use

#- name: Download and Extract {{COMPONENT}} Content
#  ansible.builtin.include_role:
#    name: common
#  tasks_from: download
#
- name: Download and Extract {{COMPONENT}} Content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: CleanUp Old Content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy App Content
  become_user: roboshop
  ansible.builtin.copy:
    dest: /home/roboshop/catalogue/
    src: /tmp/catalogue-main/
    remote_src: yes

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Copy SystemD File
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Start catalogue Service
  ansible.builtin.systemd:
    name:  catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes
