- name: Configure YUM repos.
  ansible.builtin.shell: curl -fssL https://rpm.nodesource.com/setup.lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
	name:
	  - nodejs
	  - gcc-c++
	state: installed

- name: Add Application User
  ansible.builtin.user:
	name: roboshop
	comment: Roboshop Project Application User

- name: Download and Extract {{COMPONENT}} Content
  ansible.builtin.include_roles:
	name: common
	tasks_from: download

- name: CleanUp Old Content
  ansible.builtin.file:
	path: /home/roboshop/{{COMPONENT}}
	state: absent

- name: Copy App Content
  become_user: roboshop
  ansible.builtin.copy:
	dest: /home/roboshop/{{COMPONENT}}/
	src: /tmp/{{COMPONENT}}-main/
  remote_src: yes

- name: Install NodeJS Dependencies
  become_user: roboshop
  community.general.npm:
	path: /home/roboshop/{{COMPONENT}}

- name: Copy SystemD File
  ansible.builtin.copy:
	src: systemd.service
	dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} Service
  ansible.builtin.systemd:
	name:  "{{COMPONENT}}"
	state: restarted
	enabled: yes
	daemon_reload: yes
